### ISSUE TITLE
Gem includes heavy test files unnecessarily

### ISSUE THREAD

**Issue by Ferdy89** [savonrb/wasabi#68]
The `gemspec` lists the files for the gem as
```ruby
s.files = `git ls-files`.split("\n")
```
This includes all the files in the `spec` directory which add up to 3.4MB. I believe none of these files are used out of the tests, making them unnecessary when bundling the gem.

This causes the gem to take longer to install (source code is only 34KB) and it also slightly hurts applications hosted in platforms with size limit, like Heroku (300MB).

I believe a solution for this should simply be to change that line to be
```ruby
s.files = `git ls-files -- lib/*`.split("\n")
```
Just like the `s.test_files` and `s.executables` lines in the `gemspec` do. I'd be happy to make a PR for this.

**Comment by olleolleolle** [comment]
For inspiration: Here's a comparable solution to the same problem

https://github.com/cucumber/aruba/pull/721

**Comment by utkarsh2102** [comment]
Hello,

For more inspiration: https://github.com/cucumber/cucumber-rails/pull/476, https://github.com/mvz/gir_ffi/pull/175, and so many more.
Using `git` to produce a list of files is problematic. This, I heartily believe, can be replaced via a simple Ruby alternative.

[rubocop-packaging](https://github.com/utkarsh2102/rubocop-packaging), an extension of RuboCop, was born because we faced a lot of such problems while maintaining gems in downstream (Debian, specifically).

**Comment by utkarsh2102** [comment]
@olleolleolle, would you be interested? Should I raise a PR?

**Comment by olleolleolle** [comment]
We would love a PR!

Wishlist: include the smallest amount of files, avoid using Rake to make the selection. A glob pattern plus explicit files is easiest, I think. 

Thanks for this! It's reducing sizes in many places.

**Comment by utkarsh2102** [comment]
Thanks, @olleolleolle, raised via #89! :tada: 
Also, thanks, @Ferdy89, for raising this. This is really an important issue! :100:
